version: "3.8"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  db:
    image: mysql:8.0
    ports:
      - '6603:3306'
    environment:
      MYSQL_DATABASE: web
      MYSQL_ROOT_PASSWORD: 123456

  php:
    build: .
    volumes:
      - ./code:/code
    depends_on:
      - db
    links:
      - db
